### ISSUE TITLE
Failed to load the extension "web_search".

### ISSUE THREAD

**Issue by bunnywaffle** [simbake/web_search#3]
After installing this extension and running with the --extension web_search flag, it gives me this error:

```
Traceback (most recent call last):
  File "G:\LLM\oobabooga_windows\text-generation-webui\modules\extensions.py", line 35, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "G:\LLM\oobabooga_windows\text-generation-webui\extensions\web_search\script.py", line 3, in <module>
    from googlesearch import search
ModuleNotFoundError: No module named 'googlesearch'
```
![image](https://github.com/simbake/web_search/assets/100540808/b706eb7f-0335-441e-befa-dd5f26752644)

**Comment by simbake** [comment]
Hi, go to oobaboga install dir and launch cmd_windows.bat then run ```pip install googlesearch-python```. This will install the missing module, then restart webui with the web_search extension flag as before. I will update the readme to guide people on different platforms.

**Comment by bunnywaffle** [comment]
Thanks, it looks like it worked.

![image](https://github.com/simbake/web_search/assets/100540808/2c44b26f-87e6-4d4b-9d75-6831fff4b993)

**Comment by simbake** [comment]
Great! Just enable the checkbox in the ui, ```Enable Google search``` and you can now search in the chat.
