### ISSUE TITLE
[Bug] Line 32: query = user_input.strip("search").strip()

### ISSUE THREAD

**Issue by bklynate** [simbake/web_search#4]
The issue i'm encountering stems from how Python's strip() method works. The strip() function removes the characters provided in its argument from the beginning and end of a string. In your example, when you call strin.strip("search").strip(), you're removing all instances of the characters "s", "e", "a", "r", "c", and "h" from both the beginning and end of the string "what is the current record of the Yankees".

To remove only the word "search" from the beginning of a string, you can use Python's replace() method, which replaces occurrences of a substring with another substring.

`query = user_input.replace("search", "").strip()`

**Comment by simbake** [comment]
I see what you mean, thanks for pointing this out. I will update the code.

**Comment by bklynate** [comment]
I could make the change and raise a PR

**Comment by simbake** [comment]
I already made the change and will push it soon. I am working on other updates for the extension also. I will push them all at once. Thanks

**Comment by bklynate** [comment]
@simbake Can you share the code or branch with the changes? And when do you see yourself pushing those changes? Today?

**Comment by simbake** [comment]
Yes, Iwill push them today.

**Comment by simbake** [comment]
Hey, can you make a PR on the issue. The new changes needs a bit of tuning.

**Comment by bklynate** [comment]
Here is the PR: https://github.com/simbake/web_search/pull/5

**Comment by simbake** [comment]
The changes have been merged, many thanks.
