### ISSUE TITLE
Proper way to update

### ISSUE THREAD

**Issue by IntrovertedFL** [simbake/web_search#7]
What is the proper way to update this extension?

**Comment by simbake** [comment]
Hi, for now do not update. I am trying to fix issues with the current commit and will make a release, which you can just paste in the extensions directory.

**Comment by simbake** [comment]
You have to be in the webui python env. Run the cmd.bat or cmd.sh that came with text-gen-webui. Make sure text-gen-webui is not running.
Option 1:
- Then cd into ```cd path/of/extensions/web_search```
- Then git pull and commit the changes.
- Then ```pip install -r requirements.txt
- Done. You can now exit the cmd and run webui.

Option 2:
- Download a zip file from github master branch and unzip to extensions directory.
- Run ```cd path/of/extensions/websearch
- Run ```pip install -r requirements.txt```
- Done.

***```path/of/extensions``` is the path from the root of cmd.bat/sh(Depends if using Linux or Windows).
       e.g ```cd text-generation-webui/extensions/web_search```

**Comment by IntrovertedFL** [comment]
Thank you. :)

**Comment by simbake** [comment]
Welcome :)
